name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B '-Dfile.encoding=UTF-8' '-Dstdout.encoding=UTF-8' '-Dstderr.encoding=UTF-8' -DskipTests=false clean verify
    - name: Archive test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: failsafe-reports
        path: target/failsafe-reports
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with: 
        name: app-jar
        path: target/*.jar

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: app-jar
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        files: app-jar/*.jar
        draft: false
        prerelease: false
